# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlMounts < Formula
  desc "A kubectl plugin to display pod volumes and volumeMounts."
  homepage "https://github.com/yeqianmen/kubectl-mounts"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_darwin_amd64.tar.gz"
      sha256 "0e72644632ee475febd0de822f34b5143e82b91a7f00045d2f81477733992f22"

      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_darwin_arm64.tar.gz"
      sha256 "231dd6b87009c5f6dc3df9e9866d9c50c3378445e258686422829abb010fc03b"

      def install
        bin.install "kubectl-mounts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_linux_amd64.tar.gz"
      sha256 "ca00052ede1f27c86a1844c04d1b6b90ca0a62276fec57719f60b2de6f8321dc"
      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_linux_arm.tar.gz"
      sha256 "b49213e9dfda2bcb139dc5c58019b703914f83f2ab31f6b8fcd9f7017ebeb7c4"
      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_linux_arm64.tar.gz"
      sha256 "3cdfad2e6ef9d8a8a9baf45d58b970a933c10e4095303374be0ac8b34bde2e09"
      def install
        bin.install "kubectl-mounts"
      end
    end
  end

  def caveats
    <<~EOS
      This plugin is installed as `kubectl-mounts`. You can also use it by running:
        kubectl mounts
    EOS
  end

  test do
    system "#{bin}/kubectl-mounts --version"
  end
end
