# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlMounts < Formula
  desc "A kubectl plugin to display pod volumes and volumeMounts."
  homepage "https://github.com/yeqianmen/kubectl-mounts"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_darwin_amd64.tar.gz"
      sha256 "1c1cec6a8567e3e1194609f00a0c1cc57de32477402fb3839a55b01df04f4fbf"

      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_darwin_arm64.tar.gz"
      sha256 "46abab46b0ae9709f5c7f962cb42393b8037e5207f0de71299b7c3bfba3be47d"

      def install
        bin.install "kubectl-mounts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_linux_amd64.tar.gz"
      sha256 "8402fd43d67878d1c86f3622c2a369a0fda4e7ffaddf7d50d92bebb5286b6ce7"
      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_linux_arm.tar.gz"
      sha256 "7ab7ecb61336f978d6b184875f2bdaf661f713d04ce5bf078adc7b6d524acb6f"
      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_linux_arm64.tar.gz"
      sha256 "f98ca608bf812547253b9cc0b08076785974816b516dd6f55665d6bf528751e7"
      def install
        bin.install "kubectl-mounts"
      end
    end
  end

  def caveats
    <<~EOS
      This plugin is installed as `kubectl-mounts`. You can also use it by running:
        kubectl mounts
    EOS
  end

  test do
    system "#{bin}/kubectl-mounts --version"
  end
end
