# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlMounts < Formula
  desc "A kubectl plugin to display pod volumes and volumeMounts."
  homepage "https://github.com/yeqianmen/kubectl-mounts"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_darwin_amd64.tar.gz"
      sha256 "52a6a57a02721af3f7ec3072a4798675140f96c2abe3e583964e83661c2d8b3d"

      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_darwin_arm64.tar.gz"
      sha256 "b4f9d10abbc023ec51fb30f1b26d1336c17f8abafcf21dd1e88f84a177a26b2c"

      def install
        bin.install "kubectl-mounts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_linux_amd64.tar.gz"
      sha256 "02fc310a6d9adcd4bc3a0ee6d5e5a562157970ae062e91491f6f5955567452a7"
      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_linux_arm.tar.gz"
      sha256 "08710569f50bd2db9e6e5216520a5cc29da755b8b3c93399661ca000695e404f"
      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.3/kubectl-mounts_linux_arm64.tar.gz"
      sha256 "f55aace59813c2893706602d2835fc5628f8e44973fd335b1eec121907083a53"
      def install
        bin.install "kubectl-mounts"
      end
    end
  end

  def caveats
    <<~EOS
      This plugin is installed as `kubectl-mounts`. You can also use it by running:
        kubectl mounts
    EOS
  end

  test do
    system "#{bin}/kubectl-mounts --version"
  end
end
