# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlMounts < Formula
  desc "A kubectl plugin to display pod volumes and volumeMounts."
  homepage "https://github.com/yeqianmen/kubectl-mounts"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_darwin_amd64.tar.gz"
      sha256 "4302379b369d194fd103c97a091918b54a318a5a9b15f9f17db893a17f16127a"

      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_darwin_arm64.tar.gz"
      sha256 "5ca3506ffffbcec12aaaf351b19ebe0f3d456caebd06003d10f387940e42f063"

      def install
        bin.install "kubectl-mounts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_linux_amd64.tar.gz"
      sha256 "bfd96f924ba91ff7572548b77993f11800a77b246c52d3e497983ca6a90d8670"
      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_linux_arm.tar.gz"
      sha256 "c8b9e57d4834d07a06b32096e2fd538a4e7d06f4590fbeb69b81b96e4baa30a6"
      def install
        bin.install "kubectl-mounts"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yeqianmen/kubectl-mounts/releases/download/v0.1.1/kubectl-mounts_linux_arm64.tar.gz"
      sha256 "1ddff6e27d903b2d50c2d826dd657940235f3b13af7d6c447cd3160821637084"
      def install
        bin.install "kubectl-mounts"
      end
    end
  end

  def caveats
    <<~EOS
      This plugin is installed as `kubectl-mounts`. You can also use it by running:
        kubectl mounts
    EOS
  end

  test do
    system "#{bin}/kubectl-mounts --version"
  end
end
